name: Deploy website

on:
  push:
    branches: [ "main" ] 

    #branch que estemos trabajando, en este caso main
    #Podriamos cambiarlo eventualmente a develop
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Netlify
        run: pnpm add -g netlify-cli

      - name: Install Dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy --prod \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}